In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('FuelConsumption.csv')
FuelConsumption_df = pd.DataFrame(data)
FuelConsumption_df

,Year,MAKE,MODEL,VEHICLE CLASS,ENGINE SIZE,CYLINDERS,TRANSMISSION,FUEL,FUEL CONSUMPTION,COEMISSIONS
0,2000,ACURA,1.6EL,COMPACT,1.6,4,A4,X,10.5,216
1,2000,ACURA,1.6EL,COMPACT,1.6,4,M5,X,9.8,205
2,2000,ACURA,3.2TL,MID-SIZE,3.2,6,AS5,Z,13.7,265
3,2000,ACURA,3.5RL,MID-SIZE,3.5,6,A4,Z,15.0,301
4,2000,ACURA,INTEGRA,SUBCOMPACT,1.8,4,A4,X,11.4,230
...,...,...,...,...,...,...,...,...,...,...
634,2000,VOLVO,V70 AWD TURBO,STATION WAGON - MID-SIZE,2.4,5,A4,Z,14.4,288
635,2000,VOLVO,V70 GLT TURBO,STATION WAGON - MID-SIZE,2.4,5,A4,Z,13.6,274
636,2000,VOLVO,V70 T5 TURBO,STATION WAGON - MID-SIZE,2.3,5,A4,Z,13.9,274
637,2000,VOLVO,V70 T5 TURBO,STATION WAGON - MID-SIZE,2.3,5,M5,Z,13.0,260
638,2000,VOLVO,V70R AWD TURBO,STATION WAGON - MID-SIZE,2.4,5,A5,Z,14.7,299

In [5]:
columns_to_drop = ['FUEL CONSUMPTION', 'COEMISSIONS', 'Year']
FuelConsumption_df.drop(columns= columns_to_drop, implace= True)

TypeError: DataFrame.drop() got an unexpected keyword argument 'implace'